// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glrtytxdmfxowefodjux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdscnR5dHhkbWZ4b3dlZm9kanV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNTg1OTksImV4cCI6MjA2NDgzNDU5OX0.LbsFWNntkukAaMPDrUcq4V7r93vOzSbJXIkFhKs8auA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);